version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - "33062:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_PORT
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/schema/:/app-graphql/dist/schema